databases:
  - name: defect-tracking-db
    databaseName: dts_db
    user: dts_user
    plan: free

services:
  - type: web
    name: defect-tracking-system
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    envVars:
      - key: DB_URL
        fromDatabase:
          name: defect-tracking-db
          property: connectionString
      - key: DB_DRIVER
        value: org.postgresql.Driver
